/* Auto-extracted tracker categories — shared by tracker page and index.html */
const PIXORIZE_CATEGORIES = [
  {id:"vitamins",name:"Vitamins",why:"Vitamin deficiencies are among the most frequently tested biochem topics",
   videos:[
    {id:"v01",name:"Vitamin B1 (Thiamine) Biochemistry",time:"7:20"},
    {id:"v02",name:"Vitamin B1 (Thiamine) Deficiency",time:"10:51"},
    {id:"v03",name:"Vitamin B2 (Riboflavin)",time:"6:30"},
    {id:"v04",name:"Vitamin B3 (Niacin) Biochemistry",time:"7:51"},
    {id:"v05",name:"Vitamin B3 (Niacin) Deficiency and Excess",time:"8:33"},
    {id:"v06",name:"Hartnup Disease",time:"5:58"},
    {id:"v07",name:"Vitamin B5 (Pantothenic Acid)",time:"5:34"},
    {id:"v08",name:"Vitamin B6 (Pyridoxine)",time:"10:15"},
    {id:"v09",name:"Vitamin B7 (Biotin)",time:"7:53"},
    {id:"v10",name:"Vitamin B9 (Folate)",time:"3:40"},
    {id:"v11",name:"Vitamin B12 (Cobalamin) Biochemistry",time:"7:03"},
    {id:"v12",name:"Vitamins B9 and B12 Deficiencies",time:"20:09"},
    {id:"v13",name:"Vitamin A (Retinol) Biochemistry",time:"9:24"},
    {id:"v14",name:"Vitamin A (Retinol) Deficiency and Excess",time:"9:17"},
    {id:"v15",name:"Vitamin C (Ascorbic Acid) Biochemistry",time:"8:06"},
    {id:"v16",name:"Vitamin C (Ascorbic Acid) Deficiency and Excess",time:"9:02"},
    {id:"v17",name:"Vitamin D Biochemistry",time:"11:42"},
    {id:"v18",name:"Vitamin D Deficiency and Excess",time:"11:37"},
    {id:"v19",name:"Vitamin E (Tocopherol/Tocotrienol)",time:"7:23"},
    {id:"v20",name:"Vitamin K Biochemistry",time:"6:53"},
    {id:"v21",name:"Vitamin K Deficiency",time:"6:35"},
    {id:"v22",name:"Kwashiorkor and Marasmus",time:"5:57"},
    {id:"v23",name:"Zinc",time:"6:59"}
  ]},
  {id:"biochempathways",name:"Biochemical Pathways",why:"Metabolic pathway questions thread through every organ system",
   videos:[
    {id:"bp01",name:"Cori Cycle",time:"6:41"},
    {id:"bp02",name:"De Novo Purine Synthesis",time:"8:49"},
    {id:"bp03",name:"Pyruvate Metabolism",time:"11:12"},
    {id:"bp04",name:"Sorbitol (Polyol) Pathway",time:"10:18"},
    {id:"bp05",name:"Fatty Acid Synthesis (Citrate Shuttle)",time:"5:08"},
    {id:"bp06",name:"Fatty Acid Breakdown (Carnitine Shuttle)",time:"7:01"},
    {id:"bp07",name:"Ethanol Metabolism",time:"12:41"},
    {id:"bp08",name:"Urea Cycle",time:"12:58"},
    {id:"bp09",name:"Purine Salvage",time:"11:31"},
    {id:"bp10",name:"Purine Excretion",time:"9:35"},
    {id:"bp11",name:"Catecholamine Synthesis & Breakdown",time:"19:01"},
    {id:"bp12",name:"De Novo Pyrimidine Synthesis",time:"21:04"},
    {id:"bp13",name:"Homocysteine Metabolism",time:"9:29"},
    {id:"bp14",name:"Alanine (Cahill) Cycle",time:"11:16"},
    {id:"bp15",name:"Heme Synthesis",time:"17:52"},
    {id:"bp16",name:"Galactose Metabolism",time:"11:14"},
    {id:"bp17",name:"HMP Shunt (Pentose Phosphate Pathway)",time:"—"}
  ]},
  {id:"porphyrias",name:"Porphyrias",why:"AIP and PCT are classic vignettes — know urine changes and precipitating drugs",
   videos:[
    {id:"po01",name:"Acute Intermittent Porphyria (AIP)",time:"8:53"},
    {id:"po02",name:"Porphyria Cutanea Tarda (PCT)",time:"6:36"}
  ]},
  {id:"autosomal_dom",name:"Autosomal Dominant Diseases",why:"Know the key finding and inheritance pattern for each",
   videos:[
    {id:"ad01",name:"Marfan Syndrome",time:"4:45"},
    {id:"ad02",name:"Li-Fraumeni Syndrome (LFS)",time:"5:04"},
    {id:"ad03",name:"Huntington Disease",time:"5:45"},
    {id:"ad04",name:"Achondroplasia",time:"4:13"},
    {id:"ad05",name:"Job (Hyper IgE) Syndrome",time:"4:22"},
    {id:"ad06",name:"HHT",time:"3:45"},
    {id:"ad07",name:"Hereditary Spherocytosis",time:"6:42"},
    {id:"ad08",name:"von Hippel-Lindau (VHL)",time:"4:36"},
    {id:"ad09",name:"MEN 1",time:"5:02"},
    {id:"ad10",name:"MEN 2",time:"4:29"},
    {id:"ad11",name:"Von Recklinghausen Disease (NF I)",time:"4:22"},
    {id:"ad12",name:"Neurofibromatosis Type II (NF II)",time:"2:18"},
    {id:"ad13",name:"Myotonic Dystrophy",time:"3:51"},
    {id:"ad14",name:"ADPKD",time:"6:27"}
  ]},
  {id:"metabolic",name:"Metabolic Disorders",why:"Amino acid disorders and sugar metabolism defects are high-yield",
   videos:[
    {id:"md01",name:"Albinism",time:"5:40"},
    {id:"md02",name:"Cystinuria",time:"7:38"},
    {id:"md03",name:"Maple Syrup Urine Disease",time:"6:54"},
    {id:"md04",name:"Essential Fructosuria",time:"3:49"},
    {id:"md05",name:"Hereditary Fructose Intolerance",time:"7:07"},
    {id:"md06",name:"Ornithine Transcarbamylase Deficiency",time:"7:11"},
    {id:"md07",name:"Phenylketonuria (PKU)",time:"8:53"},
    {id:"md08",name:"Alkaptonuria",time:"6:36"},
    {id:"md09",name:"Galactosemia",time:"12:02"},
    {id:"md10",name:"Galactokinase Deficiency",time:"6:16"},
    {id:"md11",name:"Lesch-Nyhan Syndrome",time:"6:49"},
    {id:"md12",name:"Pyruvate Kinase Deficiency",time:"8:14"},
    {id:"md13",name:"Pyruvate Dehydrogenase Deficiency",time:"5:49"},
    {id:"md14",name:"Propionic Acidemia",time:"7:54"}
  ]},
  {id:"lysosomal",name:"Lysosomal Storage Diseases",why:"High-yield for enzyme deficiencies, substrate accumulation, and ethnic associations",
   videos:[
    {id:"ls01",name:"Krabbe Disease",time:"4:43"},
    {id:"ls02",name:"Hurler and Hunter Syndromes",time:"7:54"},
    {id:"ls03",name:"Fabry Disease",time:"5:33"},
    {id:"ls04",name:"Tay-Sachs and Niemann-Pick",time:"7:16"},
    {id:"ls05",name:"Gaucher Disease",time:"3:53"},
    {id:"ls06",name:"Metachromatic Leukodystrophy",time:"4:45"},
    {id:"ls07",name:"I-Cell Disease",time:"8:52"}
  ]},
  {id:"glycogen",name:"Glycogen Storage Diseases",why:"Pompe, Von Gierke, Cori, and McArdle are the four to know",
   videos:[
    {id:"gs01",name:"Pompe Disease (Type II)",time:"5:16"},
    {id:"gs02",name:"Von Gierke (Type I)",time:"5:05"},
    {id:"gs03",name:"Cori Disease (Type III)",time:"5:00"},
    {id:"gs04",name:"McArdle Disease (Type V)",time:"5:06"}
  ]},
  {id:"chromosomal",name:"Chromosomal Abnormalities",why:"Trisomies and sex chromosome disorders appear on every exam",
   videos:[
    {id:"ch01",name:"Down Syndrome (Trisomy 21)",time:"10:53"},
    {id:"ch02",name:"Edwards Syndrome (Trisomy 18)",time:"7:54"},
    {id:"ch03",name:"Patau Syndrome (Trisomy 13)",time:"6:22"},
    {id:"ch04",name:"Klinefelter Syndrome",time:"7:09"},
    {id:"ch05",name:"Turner Syndrome",time:"8:43"},
    {id:"ch06",name:"Williams Syndrome",time:"6:58"},
    {id:"ch07",name:"Cri du Chat Syndrome",time:"3:38"},
    {id:"ch08",name:"Imprinting",time:"5:31"}
  ]},
  {id:"collagen",name:"Collagen Related Disorders",why:"Collagen synthesis steps and associated diseases are very high-yield",
   videos:[
    {id:"co01",name:"Alport Syndrome",time:"5:39"},
    {id:"co02",name:"Menkes Disease",time:"7:32"},
    {id:"co03",name:"Osteogenesis Imperfecta (Brittle Bone Disease)",time:"6:50"},
    {id:"co04",name:"Collagen Synthesis",time:"11:45"},
    {id:"co05",name:"Ehlers-Danlos Syndrome",time:"9:45"},
    {id:"co06",name:"Goodpasture Syndrome",time:"6:12"}
  ]},
  {id:"dnarepair",name:"DNA Repair",why:"DNA repair pathway disorders are classic vignette setups",
   videos:[
    {id:"dr01",name:"Lynch Syndrome",time:"9:40"},
    {id:"dr02",name:"Xeroderma Pigmentosum",time:"5:54"},
    {id:"dr03",name:"Ataxia-Telangiectasia",time:"7:44"},
    {id:"dr04",name:"Bloom Syndrome",time:"4:39"},
    {id:"dr05",name:"G6PD Deficiency",time:"—"}
  ]},
  {id:"misc",name:"Miscellaneous",why:"These span multiple systems and are all individually high-yield",
   videos:[
    {id:"mi01",name:"Chediak-Higashi Syndrome",time:"10:09"},
    {id:"mi02",name:"Bruton (X-linked) Agammaglobulinemia",time:"9:06"},
    {id:"mi03",name:"Familial Adenomatous Polyposis (FAP)",time:"10:26"},
    {id:"mi04",name:"Lactase Deficiency",time:"10:04"},
    {id:"mi05",name:"McCune-Albright Syndrome",time:"8:17"},
    {id:"mi06",name:"Hexokinase vs Glucokinase",time:"14:21"},
    {id:"mi07",name:"COP I & II and Clathrin",time:"7:29"},
    {id:"mi08",name:"Kartagener Syndrome (Primary Ciliary Dyskinesia)",time:"8:34"},
    {id:"mi09",name:"Peutz-Jeghers Syndrome",time:"8:04"},
    {id:"mi10",name:"Cystic Fibrosis Overview",time:"8:33"},
    {id:"mi11",name:"Medicare vs Medicaid",time:"11:34"},
    {id:"mi12",name:"Duchenne and Becker Muscular Dystrophy",time:"11:09"},
    {id:"mi13",name:"Yolk Sac Tumor",time:"4:08"},
    {id:"mi14",name:"Burkitt Lymphoma",time:"6:35"},
    {id:"mi15",name:"Rett Syndrome",time:"4:30"},
    {id:"mi16",name:"Fragile X Syndrome",time:"8:18"},
    {id:"mi17",name:"Whipple's Disease",time:"6:05"},
    {id:"mi18",name:"Osteoid Osteoma vs Osteoblastoma",time:"8:40"},
    {id:"mi19",name:"T1 vs T2 MRIs",time:"4:25"},
    {id:"mi20",name:"Cystic Fibrosis Complications",time:"13:04"},
    {id:"mi21",name:"Coagulation Panel",time:"8:38"},
    {id:"mi22",name:"Homocystinuria Findings",time:"10:09"},
    {id:"mi23",name:"HMP Shunt (Pentose Phosphate Pathway)",time:"—"},
    {id:"mi24",name:"Microscopic Polyangiitis",time:"11:22"},
    {id:"mi25",name:"Pinealoma",time:"4:39"},
    {id:"mi26",name:"Systemic Primary Carnitine Deficiency",time:"—"},
    {id:"mi27",name:"Abetalipoproteinemia",time:"—"},
    {id:"mi28",name:"Wegener's Granulomatosis",time:"14:05"},
    {id:"mi29",name:"MCAD Deficiency",time:"9:14"},
    {id:"mi30",name:"Apolipoproteins",time:"7:29"},
    {id:"mi31",name:"Hyperchylomicronemia",time:"3:55"},
    {id:"mi32",name:"Hypercholesterolemia",time:"4:53"},
    {id:"mi33",name:"Dysbetalipoproteinemia",time:"2:54"},
    {id:"mi34",name:"Hypertriglyceridemia",time:"—"},
    {id:"mi35",name:"Propionic Acid Pathway",time:"11:10"},
    {id:"mi36",name:"ABG",time:"6:15"},
    {id:"mi37",name:"CMP",time:"8:13"},
    {id:"mi38",name:"BMP (Chem7) Fishbone",time:"7:41"},
    {id:"mi39",name:"CBC",time:"7:06"}
  ]},
  {id:"neuro_disorders",name:"Neurological Disorders",why:"CNS tumors are classic one-liners — histology, location, and patient age distinguish them",
   videos:[
    {id:"nd01",name:"Craniopharyngioma",time:"8:09"},
    {id:"nd02",name:"Ependymoma",time:"7:04"},
    {id:"nd03",name:"Schwannoma",time:"9:08"},
    {id:"nd04",name:"Oligodendroglioma",time:"5:49"},
    {id:"nd05",name:"Meningioma",time:"7:54"},
    {id:"nd06",name:"Glioblastoma Multiforme (Grade IV Astrocytoma)",time:"7:07"},
    {id:"nd07",name:"Tuberous Sclerosis",time:"9:53"},
    {id:"nd08",name:"Charcot-Marie-Tooth Disease",time:"7:35"},
    {id:"nd09",name:"Tension Headache",time:"6:31"}
  ]},
  {id:"toxicology",name:"Toxicology",why:"Toxidromes and antidotes — know the mechanism and the antidote",
   videos:[
    {id:"tx01",name:"Cyanide Poisoning",time:"10:09"},
    {id:"tx02",name:"Tetrodotoxin",time:"6:22"},
    {id:"tx03",name:"Methanol Poisoning",time:"6:33"},
    {id:"tx04",name:"Ethylene Glycol Poisoning",time:"8:10"},
    {id:"tx05",name:"Ciguatoxin (Ciguatera Fish Poisoning)",time:"5:47"},
    {id:"tx06",name:"Spoiled Fish (Scombroid) Poisoning",time:"4:42"},
    {id:"tx07",name:"Carbon Monoxide Poisoning",time:"11:11"},
    {id:"tx08",name:"Amanita Phalloides",time:"—"}
  ]},
  {id:"peroxisome",name:"Peroxisome Disorders",why:"Zellweger and adrenoleukodystrophy are the key peroxisomal diseases",
   videos:[
    {id:"px01",name:"Zellweger Syndrome",time:"4:09"},
    {id:"px02",name:"Adrenoleukodystrophy",time:"6:16"},
    {id:"px03",name:"Refsum Disease",time:"9:19"}
  ]},
  {id:"mitochondrial",name:"Mitochondrial Diseases",why:"Mitochondrial inheritance (maternal) and MELAS are classic board questions",
   videos:[
    {id:"mt01",name:"Leber Hereditary Optic Neuropathy",time:"3:49"},
    {id:"mt02",name:"Mitochondrial Myopathies",time:"9:30"}
  ]},
  {id:"immunoglobulins",name:"Immunoglobulins",why:"Ig class functions, switching, and deficiency syndromes are tested frequently",
   videos:[
    {id:"ig01",name:"IgA",time:"6:45"},
    {id:"ig02",name:"IgG",time:"8:56"},
    {id:"ig03",name:"IgM",time:"7:06"},
    {id:"ig04",name:"IgE",time:"9:25"},
    {id:"ig05",name:"IgD",time:"2:25"}
  ]},
  {id:"complement",name:"Complement System",why:"Complement pathways, C3b opsonization, MAC, and deficiency diseases appear on nearly every exam",
   videos:[
    {id:"cp01",name:"Common Complement Pathway",time:"13:41"},
    {id:"cp02",name:"Classical Complement Pathway",time:"7:04"},
    {id:"cp03",name:"Alternative Complement Pathway",time:"7:04"},
    {id:"cp04",name:"Lectin Complement Pathway",time:"5:44"}
  ]},
  {id:"celltypes",name:"Other Cell Types",why:"Neutrophil oxidative burst, mast cell mediators, and NK cell mechanisms are all high-yield",
   videos:[
    {id:"ct01",name:"Neutrophils - Overview",time:"11:32"},
    {id:"ct02",name:"Neutrophils - Granules",time:"9:35"},
    {id:"ct03",name:"Neutrophils - Oxidative Burst",time:"11:04"},
    {id:"ct04",name:"Basophils",time:"8:21"},
    {id:"ct05",name:"Eosinophils",time:"11:38"},
    {id:"ct06",name:"Mast Cells",time:"14:20"},
    {id:"ct07",name:"Monocytes / Macrophages",time:"16:26"},
    {id:"ct08",name:"Natural Killer (NK) Cells",time:"13:08"},
    {id:"ct09",name:"Dendritic Cells",time:"5:11"}
  ]},
  {id:"bcells_tcells",name:"B Cells and T Cells",why:"Lymphocyte activation, MHC restriction, and T cell differentiation form the backbone of immunology",
   videos:[
    {id:"bt01",name:"MHC I",time:"7:56"},
    {id:"bt02",name:"MHC II",time:"10:13"},
    {id:"bt03",name:"B Cells - Overview",time:"6:47"},
    {id:"bt04",name:"B Cells - Activation",time:"9:25"},
    {id:"bt05",name:"Plasma B Cells",time:"5:48"},
    {id:"bt06",name:"Memory B Cells",time:"5:27"},
    {id:"bt07",name:"T Cells - Overview",time:"3:30"},
    {id:"bt08",name:"T Cells - Activation",time:"9:34"},
    {id:"bt09",name:"T Cells - Differentiation",time:"14:56"},
    {id:"bt10",name:"Cytotoxic (Killer) T Cells",time:"6:31"},
    {id:"bt11",name:"Helper T Cells - Overview",time:"6:42"},
    {id:"bt12",name:"Th1 Cells",time:"10:15"},
    {id:"bt13",name:"Th2 Cells",time:"11:14"},
    {id:"bt14",name:"Th17 Cells",time:"6:27"},
    {id:"bt15",name:"Regulatory T Cells (Tregs)",time:"11:15"}
  ]},
  {id:"cytokines",name:"Cytokines",why:"Cytokine functions are tested directly — memorize what each one does",
   videos:[
    {id:"cy01",name:"TNF-alpha",time:"6:04"},
    {id:"cy02",name:"IL-1",time:"7:07"},
    {id:"cy03",name:"IL-2",time:"6:35"},
    {id:"cy04",name:"IL-3",time:"2:41"},
    {id:"cy05",name:"IL-4",time:"5:54"},
    {id:"cy06",name:"IL-5",time:"5:09"},
    {id:"cy07",name:"IL-6",time:"5:29"},
    {id:"cy08",name:"IL-8",time:"2:29"},
    {id:"cy09",name:"IL-10",time:"3:26"},
    {id:"cy10",name:"IL-12",time:"4:30"},
    {id:"cy11",name:"TGF-beta",time:"3:32"},
    {id:"cy12",name:"IFN-alpha and IFN-beta",time:"2:54"},
    {id:"cy13",name:"IFN-gamma",time:"8:09"}
  ]},
  {id:"immunodef",name:"Immunodeficiencies",why:"Primary immunodeficiencies are a guaranteed multi-question topic",
   videos:[
    {id:"id01",name:"Selective IgA Deficiency",time:"5:27"},
    {id:"id02",name:"DiGeorge Syndrome",time:"10:07"},
    {id:"id03",name:"Hyper-IgM Syndrome",time:"8:36"},
    {id:"id04",name:"IPEX",time:"7:09"},
    {id:"id05",name:"Leukocyte Adhesion Deficiency (LAD)",time:"9:40"},
    {id:"id06",name:"Chronic Granulomatous Disease (CGD)",time:"7:51"},
    {id:"id07",name:"IL-12 Receptor Deficiency",time:"8:58"},
    {id:"id08",name:"Wiskott-Aldrich Syndrome",time:"7:40"}
  ]},
  {id:"hypersensitivity",name:"Hypersensitivity Reactions",why:"Types I–IV — know the mechanism, timing, and prototypical disease",
   videos:[
    {id:"hs01",name:"Type 1 Hypersensitivity Reactions",time:"9:42"},
    {id:"hs02",name:"Type 2 Hypersensitivity Reactions",time:"7:33"},
    {id:"hs03",name:"Type 3 Hypersensitivity Reactions",time:"6:06"},
    {id:"hs04",name:"Type 4 Hypersensitivity Reactions",time:"5:16"}
  ]},
  {id:"transfusion",name:"Transfusion Reactions",why:"ABO incompatibility, TRALI, and febrile reactions are all independently tested",
   videos:[
    {id:"tr01",name:"Anaphylactic Transfusion Reactions",time:"4:36"},
    {id:"tr02",name:"Acute Hemolytic Transfusion Reaction",time:"10:56"},
    {id:"tr03",name:"Febrile Nonhemolytic Transfusion Reaction",time:"5:55"},
    {id:"tr04",name:"TRALI",time:"5:34"}
  ]},
  {id:"transplant",name:"Transplant Rejection",why:"Hyperacute/acute/chronic rejection and GVHD are high-yield",
   videos:[
    {id:"tp01",name:"Hyperacute Transplant Rejection",time:"5:00"},
    {id:"tp02",name:"Acute Transplant Rejection",time:"5:29"},
    {id:"tp03",name:"Chronic Transplant Rejection",time:"7:15"},
    {id:"tp04",name:"Graft vs Host Disease (GVHD)",time:"9:04"}
  ]},
  {id:"germlayer",name:"Germ Layer Derivatives",why:"Embryology questions hinge on knowing which germ layer gives rise to which tissue",
   videos:[
    {id:"gl01",name:"Ectoderm Derivatives",time:"9:56"},
    {id:"gl02",name:"Mesoderm Derivatives",time:"11:52"},
    {id:"gl03",name:"Endoderm Derivatives",time:"6:00"},
    {id:"gl04",name:"Cell Junctions",time:"17:03"},
    {id:"gl05",name:"Gap Junctions",time:"4:28"},
    {id:"gl06",name:"Tight Junctions",time:"7:51"},
    {id:"gl07",name:"Desmosomes",time:"4:44"}
  ]},
  {id:"personality",name:"Personality Disorders & Conditioning",why:"Cluster A/B/C and conditioning types are bread-and-butter behavioral science",
   videos:[
    {id:"ps01",name:"Cluster A Personality Disorders",time:"7:31"},
    {id:"ps02",name:"Cluster B Personality Disorders",time:"8:03"},
    {id:"ps03",name:"Cluster C Personality Disorders",time:"7:19"},
    {id:"ps04",name:"Classical Conditioning",time:"4:47"},
    {id:"ps05",name:"Operant Conditioning",time:"4:48"}
  ]},
  {id:"cytoskeleton",name:"Cytoskeleton",why:"Microtubule/microfilament function underlies several drug MOAs (colchicine, vinca alkaloids)",
   videos:[
    {id:"cs01",name:"Cytoskeleton",time:"9:41"},
    {id:"cs02",name:"Microfilaments (Actin Filaments)",time:"6:21"},
    {id:"cs03",name:"Intermediate Filaments",time:"3:20"},
    {id:"cs04",name:"Microtubules",time:"—"}
  ]},
  {id:"dyslipidemias",name:"Dyslipidemias",why:"Lipoprotein disorders, apolipoproteins, and familial dyslipidemias connect to CV risk",
   videos:[
    {id:"dl01",name:"Dyslipidemias (Overview)",time:"21:56"}
  ]}
];
